### ISSUE TITLE
Loading Bug

### ISSUE THREAD

**Issue by gte619n** [b-yp/logseq-image-editor#3]
I load an image from the block by right clicking the block and selecting "image editor." After editing a few images, I am no longer able to load images. The editor simply shows a blank screen:

<img width="1512" alt="image" src="https://github.com/b-yp/logseq-image-editor/assets/223900/0b7daa98-93f0-439f-8625-26b192877e1a">

If I quit Logseq and reopen the application, the edit function will work again; however, I get the following response:

Edit Image A >> Image A in editor.
Edit Image B >> Image A still in editor.
Edit Image B >> Image B in editor.
Edit Image C >> Image B in editor.
Edit Image C >> Image C in editor.
Edit Image D >> No image Found
Edit Image D >> Editor loads, but blank.

**Comment by b-yp** [comment]
This may be a bug, but it's too late now and I don't have time to look carefully. Tomorrow, I will go through it in detail based on your description to see if I can find the problem.

**Comment by b-yp** [comment]
Fixed

**Comment by gte619n** [comment]
So I upgraded to 1.10 and I'm still getting some weird loading issues. Sometimes, I just get a blank screen. How can I help diagnose?

**Comment by b-yp** [comment]
If convenient, you can send the block content to help diagnose or record a GIF animation.

**Comment by gte619n** [comment]
I made a little video: https://www.loom.com/share/e7b924ebeac742e8a78f9b524602f57f?sid=79a02bf5-79c5-4268-8add-96f92e05a947

So, I think the issue might be that it doesn't load URLs? Only local assets?

**Comment by b-yp** [comment]
Thank you for feedback. URLs have been supported

**Comment by gte619n** [comment]
Works great!
